In [2]:
import pandas as pd

csv_file = '2024_cluster3_predictions.csv'

df = pd.read_csv(csv_file)
df.rename(columns={df.columns[0]: 'prediction'}, inplace=True)

# Generate a new column with dates dividing the year into 24 periods
df['date'] = pd.date_range(start='1/1/2024', end='31/12/2024', periods=24)

# Change the first value of the prediction column to 0
df.at[0, 'prediction'] = 60000

print(df)

    prediction                          date
0    60000.000 2024-01-01 00:00:00.000000000
1    50121.380 2024-01-16 20:52:10.434782608
2    41858.620 2024-02-01 17:44:20.869565217
3    52709.746 2024-02-17 14:36:31.304347826
4    46157.890 2024-03-04 11:28:41.739130435
5    45872.492 2024-03-20 08:20:52.173913044
6    49109.125 2024-04-05 05:13:02.608695652
7    46092.684 2024-04-21 02:05:13.043478262
8    48680.230 2024-05-06 22:57:23.478260870
9    50243.508 2024-05-22 19:49:33.913043478
10   49964.188 2024-06-07 16:41:44.347826088
11   51289.080 2024-06-23 13:33:54.782608696
12   46590.500 2024-07-09 10:26:05.217391304
13   53914.340 2024-07-25 07:18:15.652173914
14   44794.445 2024-08-10 04:10:26.086956524
15   48293.910 2024-08-26 01:02:36.521739132
16   51784.863 2024-09-10 21:54:46.956521740
17   43844.970 2024-09-26 18:46:57.391304348
18   47306.305 2024-10-12 15:39:07.826086956
19   52181.860 2024-10-28 12:31:18.260869568
20   52234.820 2024-11-13 09:23:28.695652176
21   45398.805 2024-11-29 06:15:39.130434784
22   49176.777 2024-12-15 03:07:49.565217392
23   49328.080 2024-12-31 00:00:00.000000000

In [3]:
# df to sql
import sqlite3
conn = sqlite3.connect('predictions.db')

df.to_sql('predictions', conn, if_exists='replace', index=False)

24

In [5]:
# read from sql
df = pd.read_sql_query("SELECT * FROM predictions", conn)
print(df)

    prediction                        date
0    60000.000         2024-01-01 00:00:00
1    50121.380  2024-01-16 20:52:10.434782
2    41858.620  2024-02-01 17:44:20.869565
3    52709.746  2024-02-17 14:36:31.304347
4    46157.890  2024-03-04 11:28:41.739130
5    45872.492  2024-03-20 08:20:52.173913
6    49109.125  2024-04-05 05:13:02.608695
7    46092.684  2024-04-21 02:05:13.043478
8    48680.230  2024-05-06 22:57:23.478260
9    50243.508  2024-05-22 19:49:33.913043
10   49964.188  2024-06-07 16:41:44.347826
11   51289.080  2024-06-23 13:33:54.782608
12   46590.500  2024-07-09 10:26:05.217391
13   53914.340  2024-07-25 07:18:15.652173
14   44794.445  2024-08-10 04:10:26.086956
15   48293.910  2024-08-26 01:02:36.521739
16   51784.863  2024-09-10 21:54:46.956521
17   43844.970  2024-09-26 18:46:57.391304
18   47306.305  2024-10-12 15:39:07.826086
19   52181.860  2024-10-28 12:31:18.260869
20   52234.820  2024-11-13 09:23:28.695652
21   45398.805  2024-11-29 06:15:39.130434
22   49176.777  2024-12-15 03:07:49.565217
23   49328.080         2024-12-31 00:00:00